// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	// models "github.com/go-park-mail-ru/2022_2_TikTikIVProd/models"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryI is an autogenerated mock type for the RepositoryI type
type RepositoryI struct {
	mock.Mock
}

// AddFriend provides a mock function with given fields: friends
func (_m *RepositoryI) AddFriend(friends models.Friends) error {
	ret := _m.Called(friends)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Friends) error); ok {
		r0 = rf(friends)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckFriends provides a mock function with given fields: friends
func (_m *RepositoryI) CheckFriends(friends models.Friends) (bool, error) {
	ret := _m.Called(friends)

	var r0 bool
	if rf, ok := ret.Get(0).(func(models.Friends) bool); ok {
		r0 = rf(friends)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Friends) error); ok {
		r1 = rf(friends)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFriend provides a mock function with given fields: friends
func (_m *RepositoryI) DeleteFriend(friends models.Friends) error {
	ret := _m.Called(friends)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Friends) error); ok {
		r0 = rf(friends)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectFriends provides a mock function with given fields: id
func (_m *RepositoryI) SelectFriends(id int) ([]models.User, error) {
	ret := _m.Called(id)

	var r0 []models.User
	if rf, ok := ret.Get(0).(func(int) []models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepositoryI interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryI creates a new instance of RepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryI(t mockConstructorTestingTNewRepositoryI) *RepositoryI {
	mock := &RepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
