// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAttachmentsServer is an autogenerated mock type for the UnsafeAttachmentsServer type
type UnsafeAttachmentsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAttachmentsServer provides a mock function with given fields:
func (_m *UnsafeAttachmentsServer) mustEmbedUnimplementedAttachmentsServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeAttachmentsServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAttachmentsServer creates a new instance of UnsafeAttachmentsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAttachmentsServer(t mockConstructorTestingTNewUnsafeAttachmentsServer) *UnsafeAttachmentsServer {
	mock := &UnsafeAttachmentsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
