// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthServer is an autogenerated mock type for the UnsafeAuthServer type
type UnsafeAuthServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthServer provides a mock function with given fields:
func (_m *UnsafeAuthServer) mustEmbedUnimplementedAuthServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeAuthServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAuthServer creates a new instance of UnsafeAuthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAuthServer(t mockConstructorTestingTNewUnsafeAuthServer) *UnsafeAuthServer {
	mock := &UnsafeAuthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
