// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(in *jlexer.Lexer, out *ReqCommunityCreate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar_id":
			out.AvatarID = uint64(in.Uint64())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(out *jwriter.Writer, in ReqCommunityCreate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.AvatarID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReqCommunityCreate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReqCommunityCreate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReqCommunityCreate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReqCommunityCreate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(l, v)
}
func easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(in *jlexer.Lexer, out *Community) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "owner_id":
			out.OwnerID = uint64(in.Uint64())
		case "avatar_id":
			out.AvatarID = uint64(in.Uint64())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "create_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreateDate).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(out *jwriter.Writer, in Community) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.OwnerID))
	}
	{
		const prefix string = ",\"avatar_id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AvatarID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"create_date\":"
		out.RawString(prefix)
		out.Raw((in.CreateDate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Community) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Community) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson798dd0c9EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Community) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Community) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson798dd0c9DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels1(l, v)
}
