// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3994edd1DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(in *jlexer.Lexer, out *Friends) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id1":
			out.Id1 = uint64(in.Uint64())
		case "Id2":
			out.Id2 = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3994edd1EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(out *jwriter.Writer, in Friends) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id1\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id1))
	}
	{
		const prefix string = ",\"Id2\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Id2))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Friends) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3994edd1EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Friends) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3994edd1EncodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Friends) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3994edd1DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Friends) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3994edd1DecodeGithubComGoParkMailRu20222TikTikIVProdMainAppModels(l, v)
}
