version: "3.5"
services:
  ws_pg:
    image: "postgres:latest"
    ports:
      - "13080:5432"
    networks:
      - mynetwork
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d/
      - ./gen:/home/gen
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:latest
    command: --requirepass "ws_redis_password"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  server:
    build: ./MainApp
    restart: always
    volumes:
      - ./images:/images
    depends_on:
      - ws_pg
      - auth_mvs
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  auth_mvs:
    build: ./AuthMicroservice
    restart: always
    volumes:
      - ./images:/images
    depends_on:
      - redis
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  image_mvs:
    build: ./ImageMicroservice
    restart: always
    volumes:
      - ./images:/images
    depends_on:
      - ws_pg
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  chat_mvs:
    build: ./ChatMicroservice
    restart: always
    volumes:
      - ./images:/images
    depends_on:
      - ws_pg
    ports:
      - "8083:8083"
    networks:
      - mynetwork

  user_mvs:
    build: ./UserMicroservice
    restart: always
    volumes:
      - ./images:/images
    depends_on:
      - ws_pg
    ports:
      - "8084:8084"
    networks:
      - mynetwork



networks:
  mynetwork: