definitions:
  models.Image:
    properties:
      id:
        type: integer
      link:
        type: string
    type: object
  models.Post:
    properties:
      create_date:
        type: string
      firstName:
        type: string
      id:
        type: integer
      images:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      lastName:
        type: string
      message:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      avatar:
        type: integer
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      nick_name:
        type: string
      password:
        type: string
    type: object
  models.UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  pkg.Error:
    properties:
      error:
        type: string
    type: object
  pkg.Response:
    properties:
      body: {}
    type: object
host: 89.208.197.127:8080
info:
  contact: {}
  title: WS Swagger API
  version: "1.0"
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: check user auth
      produces:
      - application/json
      responses:
        "200":
          description: success auth
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: no cookie
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Auth
      tags:
      - users
  /feed:
    get:
      consumes:
      - application/json
      description: Feed
      produces:
      - application/json
      responses:
        "200":
          description: success get feed
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Feed
      tags:
      - posts
  /logout:
    get:
      consumes:
      - application/json
      description: user logout
      produces:
      - application/json
      responses:
        "200":
          description: success logout
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: no cookie
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Logout
      tags:
      - users
  /signin:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: success sign in
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: invalid password
          schema:
            $ref: '#/definitions/pkg.Error'
        "404":
          description: user doesn't exist
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: SignIn
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: user sign up
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: user created
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "409":
          description: user with this email already exists
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: SignUp
      tags:
      - users
swagger: "2.0"
