definitions:
  models.Friends:
    properties:
      id_friend:
        type: integer
      id_user:
        type: integer
    type: object
  models.Image:
    properties:
      id:
        type: integer
      link:
        type: string
    type: object
  models.Post:
    properties:
      create_date:
        type: string
      id:
        type: integer
      images:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      message:
        type: string
      user_first_name:
        type: string
      user_id:
        type: integer
      user_last_name:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: integer
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      nick_name:
        type: string
      password:
        type: string
    type: object
  models.UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  pkg.Error:
    properties:
      error:
        type: string
    type: object
  pkg.Response:
    properties:
      body: {}
    type: object
host: 89.208.197.127:8080
info:
  contact: {}
  title: WS Swagger API
  version: "1.0"
paths:
  /auth:
    get:
      description: check user auth
      produces:
      - application/json
      responses:
        "200":
          description: success auth
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: no cookie
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Auth
      tags:
      - auth
  /feed:
    get:
      consumes:
      - application/json
      description: Feed
      produces:
      - application/json
      responses:
        "200":
          description: success get feed
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Feed
      tags:
      - posts
  /friends/add:
    post:
      consumes:
      - application/json
      description: add friend
      parameters:
      - description: friends info
        in: body
        name: friends
        required: true
        schema:
          $ref: '#/definitions/models.Friends'
      produces:
      - application/json
      responses:
        "201":
          description: friend added
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "409":
          description: friendship already exists
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: AddFriend
      tags:
      - friends
  /friends/delete:
    delete:
      consumes:
      - application/json
      description: delete friend
      parameters:
      - description: friends info
        in: body
        name: friends
        required: true
        schema:
          $ref: '#/definitions/models.Friends'
      produces:
      - application/json
      responses:
        "204":
          description: friend deleted, body is empty
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "404":
          description: friend or user doesn't exist
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: DeleteFriend
      tags:
      - friends
  /logout:
    delete:
      description: user logout
      produces:
      - application/json
      responses:
        "204":
          description: success logout, body is empty
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: no cookie
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Logout
      tags:
      - auth
  /post/{id}:
    get:
      consumes:
      - application/json
      description: Get post by id
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success get post
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.Post'
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Show a post
      tags:
      - posts
  /post/create:
    post:
      consumes:
      - application/json
      description: Create a post
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: success get post
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.Post'
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Create a post
      tags:
      - posts
  /post/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success get post
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.Post'
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Delete a post
      tags:
      - posts
  /post/update:
    post:
      consumes:
      - application/json
      description: Update a post
      parameters:
      - description: post info
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: success get post
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.Post'
              type: object
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: Update a post
      tags:
      - posts
  /signin:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: success sign in
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "401":
          description: invalid password
          schema:
            $ref: '#/definitions/pkg.Error'
        "404":
          description: user doesn't exist
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: SignIn
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: user sign up
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: user created
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "409":
          description: user with this email already exists
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: SignUp
      tags:
      - auth
  /users/{id}:
    get:
      description: get user's profile
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/pkg.Response'
            - properties:
                body:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/pkg.Error'
        "404":
          description: can't find user with such id
          schema:
            $ref: '#/definitions/pkg.Error'
        "405":
          description: invalid http method
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/pkg.Error'
      summary: GetProfile
      tags:
      - users
swagger: "2.0"
