definitions:
  delivery.Response:
    properties:
      body: {}
    type: object
  model.User:
    properties:
      avatar:
        type: integer
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      nick_name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: WS Swagger API
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: SignIn
      tags:
      - auth
swagger: "2.0"
