global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: echo 
    metrics_path: /prometheus
    static_configs:
      - targets:
        - server:8080
  - job_name: node
    metrics_path: /metrics
    static_configs:
    - targets: ["node-exporter:9100"]