// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	__ "github.com/go-park-mail-ru/2022_2_TikTikIVProd/ImageMicroservice/proto"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseI is an autogenerated mock type for the UseCaseI type
type UseCaseI struct {
	mock.Mock
}

// CreateImage provides a mock function with given fields: _a0
func (_m *UseCaseI) CreateImage(_a0 *__.Image) (*__.Nothing, error) {
	ret := _m.Called(_a0)

	var r0 *__.Nothing
	if rf, ok := ret.Get(0).(func(*__.Image) *__.Nothing); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.Nothing)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*__.Image) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImage provides a mock function with given fields: _a0
func (_m *UseCaseI) GetImage(_a0 *__.GetImageRequest) (*__.Image, error) {
	ret := _m.Called(_a0)

	var r0 *__.Image
	if rf, ok := ret.Get(0).(func(*__.GetImageRequest) *__.Image); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*__.GetImageRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostImages provides a mock function with given fields: _a0
func (_m *UseCaseI) GetPostImages(_a0 *__.GetPostImagesRequest) (*__.GetPostImagesResponse, error) {
	ret := _m.Called(_a0)

	var r0 *__.GetPostImagesResponse
	if rf, ok := ret.Get(0).(func(*__.GetPostImagesRequest) *__.GetPostImagesResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetPostImagesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*__.GetPostImagesRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCaseI interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCaseI creates a new instance of UseCaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCaseI(t mockConstructorTestingTNewUseCaseI) *UseCaseI {
	mock := &UseCaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
