// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/go-park-mail-ru/2022_2_TikTikIVProd/models"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseI is an autogenerated mock type for the UseCaseI type
type UseCaseI struct {
	mock.Mock
}

// SelectAllDialogs provides a mock function with given fields: userId
func (_m *UseCaseI) SelectAllDialogs(userId int) ([]models.Dialog, error) {
	ret := _m.Called(userId)

	var r0 []models.Dialog
	if rf, ok := ret.Get(0).(func(int) []models.Dialog); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Dialog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDialog provides a mock function with given fields: id
func (_m *UseCaseI) SelectDialog(id int) (*models.Dialog, error) {
	ret := _m.Called(id)

	var r0 *models.Dialog
	if rf, ok := ret.Get(0).(func(int) *models.Dialog); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Dialog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDialogByUsers provides a mock function with given fields: userId, friendId
func (_m *UseCaseI) SelectDialogByUsers(userId int, friendId int) (*models.Dialog, error) {
	ret := _m.Called(userId, friendId)

	var r0 *models.Dialog
	if rf, ok := ret.Get(0).(func(int, int) *models.Dialog); ok {
		r0 = rf(userId, friendId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Dialog)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userId, friendId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: message
func (_m *UseCaseI) SendMessage(message *models.Message) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUseCaseI interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCaseI creates a new instance of UseCaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCaseI(t mockConstructorTestingTNewUseCaseI) *UseCaseI {
	mock := &UseCaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
