// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	__ "github.com/go-park-mail-ru/2022_2_TikTikIVProd/MainApp/proto/image"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ImagesClient is an autogenerated mock type for the ImagesClient type
type ImagesClient struct {
	mock.Mock
}

// CreateImage provides a mock function with given fields: ctx, in, opts
func (_m *ImagesClient) CreateImage(ctx context.Context, in *__.Image, opts ...grpc.CallOption) (*__.ImageId, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *__.ImageId
	if rf, ok := ret.Get(0).(func(context.Context, *__.Image, ...grpc.CallOption) *__.ImageId); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.ImageId)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *__.Image, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImage provides a mock function with given fields: ctx, in, opts
func (_m *ImagesClient) GetImage(ctx context.Context, in *__.ImageId, opts ...grpc.CallOption) (*__.Image, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *__.Image
	if rf, ok := ret.Get(0).(func(context.Context, *__.ImageId, ...grpc.CallOption) *__.Image); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *__.ImageId, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostImages provides a mock function with given fields: ctx, in, opts
func (_m *ImagesClient) GetPostImages(ctx context.Context, in *__.GetPostImagesRequest, opts ...grpc.CallOption) (*__.GetPostImagesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *__.GetPostImagesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *__.GetPostImagesRequest, ...grpc.CallOption) *__.GetPostImagesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.GetPostImagesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *__.GetPostImagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewImagesClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewImagesClient creates a new instance of ImagesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImagesClient(t mockConstructorTestingTNewImagesClient) *ImagesClient {
	mock := &ImagesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
