// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeImagesServer is an autogenerated mock type for the UnsafeImagesServer type
type UnsafeImagesServer struct {
	mock.Mock
}

// mustEmbedUnimplementedImagesServer provides a mock function with given fields:
func (_m *UnsafeImagesServer) mustEmbedUnimplementedImagesServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeImagesServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeImagesServer creates a new instance of UnsafeImagesServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeImagesServer(t mockConstructorTestingTNewUnsafeImagesServer) *UnsafeImagesServer {
	mock := &UnsafeImagesServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
