name: Docker Compose Actions Workflow
on:
  push:
    branches: [deploy]
jobs:
  # golangci:
  #   name: linter
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.19
  #     - uses: actions/checkout@v2
  #     - name: run golangci-lint
  #       run: |
  #         go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
  #         cd MainApp && golangci-lint run ./... && cd ..
  #         cd UserMicroservice && golangci-lint run ./... && cd ..
  #         cd AuthMicroservice && golangci-lint run ./... && cd ..
  #         cd AttachmentMicroservice && golangci-lint run ./... && cd ..
  #         cd ChatMicroservice && golangci-lint run ./... && cd ..

  # tests:
  #   # needs: golangci
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.19

  #   - name: tests
  #     run: |
  #       cd MainApp && go test ./... -v && cd ..
  #       cd UserMicroservice && go test ./... -v && cd ..
  #       cd AuthMicroservice && go test ./... -v && cd ..
  #       cd AttachmentMicroservice && go test ./... -v && cd ..
  #       cd ChatMicroservice && go test ./... -v && cd ..
  
  build:
    # needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          sudo docker compose build
      - name: Push the image
        run: |
          sudo docker compose push
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: pull project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            sudo docker rm -vf $(sudo docker ps -a -q)
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd 2022_2_TikTikIVProd/
            sudo docker compose pull
      - name: run project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd 2022_2_TikTikIVProd/
            git pull
            git checkout deploy
            sudo docker-compose up -d

