// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeChatServer is an autogenerated mock type for the UnsafeChatServer type
type UnsafeChatServer struct {
	mock.Mock
}

// mustEmbedUnimplementedChatServer provides a mock function with given fields:
func (_m *UnsafeChatServer) mustEmbedUnimplementedChatServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeChatServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeChatServer creates a new instance of UnsafeChatServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeChatServer(t mockConstructorTestingTNewUnsafeChatServer) *UnsafeChatServer {
	mock := &UnsafeChatServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
